import streamlit as st
import asyncio
import time
import re
import io
from types import SimpleNamespace

# Import PDF Libraries
import markdown2
from xhtml2pdf import pisa

# Import ADK
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService

# Import Agents
from course_agents.curriculum_agent import curriculum_agent
from course_agents.content_agent import content_agent
from course_agents.review_agent import review_agent
from course_agents.quiz_agent import quiz_agent

# Set Page Layout to WIDE
st.set_page_config(page_title="AI Course Creator", page_icon="🎓", layout="wide")

st.markdown("""
    <style>
    .stTextArea textarea {font-size: 16px;}
    .stSpinner {margin-bottom: 1rem;}
    h1 {text-align: center; color: #4F8BF9;}
    h3 {border-bottom: 2px solid #f0f0f0; padding-bottom: 0.5rem; margin-top: 1rem;}
    .agent-box {padding: 1rem; border-radius: 8px; background-color: #f8f9fa; border: 1px solid #e0e0e0; margin-bottom: 1rem;}
    </style>
    """, unsafe_allow_html=True)

st.title("🎓 Autonomous AI Course Creator")

# --- UPDATED: CENTERED CAPTION ---
st.markdown(
    "<p style='text-align: center; color: #666; margin-top: -15px;'>Using <b>Google ADK</b> & <b>Gemini 2.0 Flash Lite</b> for developing this project</p>", 
    unsafe_allow_html=True
)

# --- SIDEBAR ---
with st.sidebar:
    st.header("Course Settings")
    topic = st.text_input("Topic", "Enter the topic")
    audience = st.selectbox("Audience", ["Beginners", "Intermediate", "Advanced",])
    start_btn = st.button("Build Course", type="primary")

# --- HELPERS ---
def wrap_message(text: str):
    return SimpleNamespace(role="user", parts=[SimpleNamespace(text=text)])

def extract_text(event):
    try:
        if event.content and event.content.parts:
            return event.content.parts[0].text
    except AttributeError:
        pass
    return None

def parse_modules_from_syllabus(syllabus_text):
    """Extracts module titles from the syllabus text."""
    modules = []
    if not syllabus_text: return []
    
    lines = syllabus_text.split('\n')
    for line in lines:
        clean_line = line.strip()
        if re.match(r'^(?:Module\s+\d+|Unit\s+\d+|\d+\.)[:\s-]', clean_line, re.IGNORECASE):
            clean_title = clean_line.replace('*', '').strip()
            modules.append(clean_title)
    
    if not modules:
        return ["Module 1: Fundamentals", "Module 2: Core Concepts", "Module 3: Application", "Module 4: Advanced Topics", "Module 5: Conclusion"]
    
    return modules[:5]

def create_pdf(markdown_content):
    """Converts Markdown content to a professional PDF with CSS styling."""
    html_content = markdown2.markdown(markdown_content, extras=["fenced-code-blocks", "tables", "header-ids"])

    pdf_style = """
    <html>
    <head>
        <style>
            @page {
                size: a4 portrait;
                @frame header_frame { -pdf-frame-content: header_content; left: 50pt; width: 512pt; top: 50pt; height: 40pt; }
                @frame content_frame { left: 50pt; width: 512pt; top: 90pt; height: 632pt; }
                @frame footer_frame { -pdf-frame-content: footer_content; left: 50pt; width: 512pt; top: 772pt; height: 20pt; }
            }
            body { font-family: Helvetica, sans-serif; font-size: 11pt; line-height: 1.5; color: #333; }
            h1 { color: #2c3e50; font-size: 24pt; border-bottom: 2px solid #3498db; padding-bottom: 10px; margin-top: 30px; }
            h2 { color: #34495e; font-size: 18pt; margin-top: 25px; margin-bottom: 10px; border-bottom: 1px solid #ddd; }
            h3 { color: #2980b9; font-size: 14pt; margin-top: 20px; }
            p { margin-bottom: 10px; text-align: justify; }
            code { background-color: #f4f4f4; color: #c7254e; font-family: Courier; padding: 2px 4px; }
            pre { background-color: #f8f9fa; border: 1px solid #e0e0e0; border-radius: 5px; padding: 10px; margin: 15px 0; font-family: Courier; font-size: 9pt; }
            blockquote { border-left: 4px solid #3498db; padding-left: 15px; color: #555; font-style: italic; margin: 15px 0; }
        </style>
    </head>
    <body>
        <div id="header_content" style="text-align: right; color: #888; font-size: 9pt;">Generated by AI Course Creator</div>
        <div id="footer_content" style="text-align: center; color: #888; font-size: 9pt;">Page <pdf:pagenumber></div>
        <div>%s</div>
    </body>
    </html>
    """ % html_content

    pdf_buffer = io.BytesIO()
    pisa_status = pisa.CreatePDF(io.BytesIO(pdf_style.encode("utf-8")), dest=pdf_buffer)
    if pisa_status.err: return None
    return pdf_buffer.getvalue()

# --- 🚀 PIPELINE LOGIC (3 Columns) ---
async def run_pipeline(topic, audience, c1, c2, c3):
    session = InMemorySessionService()
    session_id = "web_session"
    user_id = "web_user"
    await session.create_session(session_id=session_id, user_id=user_id, app_name="course_creator")

    full_course_content = f"# {topic}\n**Target Audience:** {audience}\n\n"

    # --- PHASE 1: SYLLABUS (Column 1) ---
    syllabus_text = ""
    with c1:
        st.subheader("1. Structure")
        with st.status("🏗️ Architect is planning...", expanded=True) as status:
            runner = Runner(agent=curriculum_agent, session_service=session, app_name="course_creator")
            msg = wrap_message(f"Create a syllabus for '{topic}' for {audience}. List exactly 5 modules. Format as 'Module X: Title'.")
            async for event in runner.run_async(session_id=session_id, user_id=user_id, new_message=msg):
                if event.is_final_response(): syllabus_text = extract_text(event)
            status.update(label="✅ Plan Ready", state="complete", expanded=False)
        st.markdown(syllabus_text)
    
    full_course_content += f"## Course Syllabus\n{syllabus_text}\n\n"
    
    modules = parse_modules_from_syllabus(syllabus_text)
    time.sleep(2)

    # --- PHASE 2: MODULAR LOOP (Filling Columns 2 & 3) ---
    progress_bar = st.progress(0)

    for i, module_title in enumerate(modules):
        progress_bar.progress((i) / len(modules))
        
        # --- HIDDEN DRAFTING & VISIBLE REVIEW (Column 2) ---
        final_lesson = ""
        with c2:
            if i == 0: st.subheader("2.Lessons of Each Module")
            
            # We combine the "Drafting" and "Polishing" visual status into one box in the Lesson column
            with st.status(f"✍️ Writing {module_title}...", expanded=True) as status:
                
                # 1. Internal Draft (Professor) - No Output shown
                status.write("Generating deep-dive draft...")
                runner_draft = Runner(agent=content_agent, session_service=session, app_name="course_creator")
                draft_prompt = f"""
                Write the FULL DETAILED LESSON for '{module_title}'.
                - Include Practical Code Examples.
                - CRITICAL: Every code block MUST be followed by an explanation.
                - Write at least 500 words.
                """
                async for event in runner_draft.run_async(session_id=session_id, user_id=user_id, new_message=wrap_message(draft_prompt)):
                    pass 
                
                # 2. Polishing (Reviewer) - Output shown
                status.write("Dean is polishing and formatting...")
                runner_rev = Runner(agent=review_agent, session_service=session, app_name="course_creator")
                rev_prompt = "Review this lesson. Improve structure, add bolding to key terms, and ensure code blocks are formatted."
                async for event in runner_rev.run_async(session_id=session_id, user_id=user_id, new_message=wrap_message(rev_prompt)):
                    if event.is_final_response(): final_lesson = extract_text(event)
                
                status.update(label=f"✅ Completed: {module_title}", state="complete", expanded=False)
            
            # Display Module Content nicely
            st.markdown(f"### {module_title}")
            with st.expander("📖 Read Lesson", expanded=True):
                st.markdown(final_lesson)
            st.divider()

        # --- QUIZ (Column 3) ---
        quiz_text = ""
        with c3:
            if i == 0: st.subheader("3. Quizzes")
            with st.spinner(f"Creating Quiz for {module_title}..."):
                runner = Runner(agent=quiz_agent, session_service=session, app_name="course_creator")
                q_prompt = f"Create a short 5-question quiz specifically for '{module_title}' based on the lesson above."
                async for event in runner.run_async(session_id=session_id, user_id=user_id, new_message=wrap_message(q_prompt)):
                    if event.is_final_response(): quiz_text = extract_text(event)
            
            with st.expander("❓ Take Quiz"):
                st.markdown(quiz_text)

        # Append to Master File
        full_course_content += f"\n# {module_title}\n\n{final_lesson}\n\n### {module_title} Quiz\n{quiz_text}\n\n<pdf:nextpage>\n"
        
        # Rate Limit Pause
        if i < len(modules) - 1:
            with c2: st.caption("⏳ Cooling down API...")
            time.sleep(10)

    progress_bar.progress(100)

    # --- FINAL DOWNLOAD ---
    st.divider()
    st.success("🎉 Course Generation Complete! All modules processed.")
    
    with st.spinner("📄 Converting to Professional PDF..."):
        pdf_bytes = create_pdf(full_course_content)
    
    if pdf_bytes:
        st.download_button("📥 Download Professional Course (.pdf)", pdf_bytes, f"{topic}_Course.pdf", "application/pdf", type="primary")
    else:
        st.download_button("📥 Download as Markdown (.md)", full_course_content, f"{topic}_Course.md")

# --- MAIN ---
if start_btn and topic:
    # 3 COLUMNS ONLY: [Syllabus (Small) | Lessons (Wide) | Quiz (Small)]
    c1, c2, c3 = st.columns([1, 2, 1]) 
    asyncio.run(run_pipeline(topic, audience, c1, c2, c3))